name: Build Sysbox Nexus Image

on:
  push:
    branches:
      - main

env:
  REGISTRY_DOCKERIO_PASS: ${{ secrets.REGISTRY_DOCKERIO_PASS }}
  REGISTRY_DOCKERIO_USER: ${{ secrets.REGISTRY_DOCKERIO_USER }}
  TAG: latest

jobs:
  dagger:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # Install Golang and check version
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
          check-latest: true

      # Install cosign and check version
      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: main
      - name: Check cosign installation
        run: cosign version

      # Use Docker to login to Dockerhub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image with dagger
      - name: Dagger
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true
      - name: Show Dagger version
        run: dagger version
      - name: Build docker image
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project update
            do --plan build-sysbox.cue versions

      # Sign image with cosign
      - name: Sign image
        shell: bash
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          cosign sign -a commit=${{ github.sha }} \
            -a "repo=${{ secrets.DOCKER_USERNAME }}/core-nexus" \
            -a "workflow=${{ github.workflow }}" \
            --key env://COSIGN_PRIVATE_KEY \
            ${{ secrets.DOCKER_USERNAME }}/core-nexus:$VERSION-sysbox && \
          cosign sign -a commit=${{ github.sha }} \
            -a "repo=${{ secrets.DOCKER_USERNAME }}/core-nexus" \
            -a "workflow=${{ github.workflow }}" \
            --key env://COSIGN_PRIVATE_KEY \
            ${{ secrets.DOCKER_USERNAME }}/core-nexus:${{ env.TAG }}-sysbox
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}